export const SIGNIN_GOOGLE = "SIGNIN_GOOGLE";
export const GET_BIRD = "GET_BIRD";
export const DELETE_BIRD = "DELETE_BIRD";
export const EDIT_BIRD = "EDIT_BIRD";
export const EDIT_BIRD_COMPLETE = "EDIT_BIRD_COMPLETE";
export const UPDATE_BIRD_COMPLETE = "UPDATE_BIRD_COMPLETE";
